[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
surrealdb = "1.0.0-beta.8"
tokio = { version = "1.24.1", features = ["full"] }
